sidebar:
  entries:
    - title: ONTAP tools for VMware vSphere
      url: /index.html
    - title: Release notes
      url: /reference_release_notes.html
    - section: Concepts
    - section: deploy
    - section: configure
    - section: protect
    - section: manage


homepage:
  tiles:
  - title: Get started
    links:
    - title: Release reference_release_notes
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2875589
    - title: Learn about ONTAP tools for VMware vSphere
      url: /Concepts/concept_virtual_storage_console_overview.html
    - title: Deploy ONTAP tools
      url: /deploy/task_deploy_ontap_tools.html
    - title: Upgrade ONTAP tools
      url: /deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html
  - title: Use ONTAP tools
    links:
    - title: Provision traditional datastores
      url: /configure/concept_configure_traditional_datastores.html
    - title: Provision vVols datastores
      url: /configure/task_provision_vvols_datastores.html
    - title: Configure role-based access control
      url: /Concepts/concept_ontap_role_based_access_control_feature_for_ontap_tools.html
    - title: Configure remote diagnostics
      url: /configure/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html
    - title: Configure high availability
      url: /Concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html
  - title: Protect and manage datastores
    links:
    - title: Protect your datastores
      url: /Concepts/concept_manage_disaster_recovery_setup_using_srm.html
    - title: Protect virtual machines
      url: /configure/concept_configure_replication_for_vvols_datastore.html
    - title: Monitor traditional datastores and virtual machines
      url: /manage/task_monitor_datastores_using_the_traditional_dashboard.html
    - title: Monitor vVols datastores and virtual machines
      url: /manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html
  - title: More resources
    links:
    - title: NetApp Knowledge Base - ONTAP tools
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider
    - title: NetApp Import Utility for SnapCenter and Virtual Storage Console Overview
      url: https://www.youtube.com/watch?v=CEQmIEzNVfA
    - title: NetApp Community - ONTAP tools
      url: https://community.netapp.com/t5/VMware-Solutions-Discussions/bd-p/vmware-solutions-discussions
