---
settings:
  name: ONTAP tools for VMware vSphere 9.10
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: ONTAP tools for VMware vSphere 9.10 docs
      url: /index.html
    - title: Release notes
      url: /release_notes.html
    - section: concepts
    - section: deploy
    - section: configure
    - section: protect
    - section: manage
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
  - title: Get started
    links:
    - title: Release notes
      url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2881273
    - title: Learn about ONTAP tools for VMware vSphere
      url: /concepts/concept_virtual_storage_console_overview.html
    - title: ONTAP tools Quick start
      url: /qsg.html
    - title: Deploy ONTAP tools
      url: /deploy/task_deploy_ontap_tools.html
    - title: Upgrade ONTAP tools
      url: /deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html
  - title: Use ONTAP tools
    links:
    - title: Provision traditional datastores
      url: /configure/task_provision_datastores.html
    - title: Provision vVols datastores
      url: /configure/task_provision_vvols_datastores.html
    - title: Configure role-based access control
      url: /concepts/concept_vcenter_server_role_based_access_control_features_in_vsc_for_vmware_vsphere.html
    - title: Configure remote diagnostics
      url: /manage/task_configure_vasa_provider_to_use_ssh_for_remote_diag_access.html
    - title: Configure high availability
      url: /concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html
  - title: Protect and manage datastores
    links:
    - title: Protect your datastores
      url: /protect/task_enable_storage_replication_adapter.html
    - title: Protect virtual machines
      url: /protect/concept_configure_replication_for_vvols_datastore.html
    - title: Monitor traditional datastores and virtual machines
      url: /manage/task_monitor_datastores_using_the_traditional_dashboard.html
    - title: Monitor vVols datastores and virtual machines
      url: /manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html
  - title: More resources
    links:
    - title: Documentation for earlier versions of ONTAP tools for VMware
      url: https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=63792
    - title: NetApp Knowledge Base - ONTAP tools
      url: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/VSC_and_VASA_Provider
    - title: NetApp Import Utility - Video
      url: https://www.youtube.com/watch?v=CEQmIEzNVfA
    - title: NetApp Community - ONTAP tools
      url: https://community.netapp.com/t5/VMware-Solutions-Discussions/bd-p/vmware-solutions-discussions
