sidebar:
  entries:
    - title: ONTAP tools for VMware vSphere
      url: "/index.html"
    - section: Concepts
    - section: get-started
    - section: configure
    - section: protect
    - section: manage
    - section: monitor

homepage:
  tiles:
  - title: Get started
    links:
    - title: Learn about ONTAP tools for VMware vSphere
      summary: This is the description of the link target
      url: Concepts/concept_virtual_storage_console_overview.html
    - title: Upgrade ONTAP tools
      url: upgrade/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html
