sidebar:
  entries:
    - title: ONTAP tools for VMware vSphere
      url: "/index.html"
    - section: deploy
    - section: manage

homepage:
  tiles:
  - title: This is the title of a tile
    links:
    - title: This is the title of a link
      summary: This is the description of the link target
      url: deploy/index.html
