---
settings:
  name: ONTAP tools for VMware vSphere 9.13
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - version-number: "9.13"
      url: /ontap-tools-vmware-vsphere
    - version-number: "9.12"
      url: /ontap-tools-vmware-vsphere-912
    - version-number: "9.11"
      url: /ontap-tools-vmware-vsphere-911
    - version-number: "9.10"
      url: /ontap-tools-vmware-vsphere-910
    - version-number: "9.8"
      url: /ontap-tools-vmware-vsphere-98

sidebar:
  entries:
    - title: ONTAP tools for VMware vSphere 9.13 docs
      url: /index.html
    - title: Release notes
      url: /release_notes.html
    - section: concepts
    - section: deploy
    - section: configure
    - section: protect
    - section: manage
    - title: Legal notices
      url: /legal-notices.html
