---
permalink: deploy/concept_how_to_download_ontap_tools.html
sidebar: sidebar
keywords:
summary: 'You can download the .ova file for ONTAP tools for VMware vSphere from the NetApp Support Site.'
---
= How to download ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can download the _.ova_ file for ONTAP tools for VMware vSphere from the NetApp Support Site.

The _.ova_ file includes the ONTAP tools. When the deployment is complete, all the three products are installed in your environment. By default, VSC starts working as soon as you decide on the subsequent deployment model and choose whether to enable VASA Provider and SRA based on your requirements.

You can download ONTAP tools from the https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab[NetApp Support Site] by using the software download page.

If you want to enable SRA in your deployment of ONTAP tools, then you must have installed the SRA plug-in on the Site Recovery Manager (SRM) server. You can download the installation file for the SRA plug-in from the *Storage Replication Adapter for ONTAP* menu in the Software Downloads section.
