---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html
sidebar: sidebar
keywords:
summary: 'The 9.x releases of ONTAP tools for VMware vSphere support in-place upgrade to the latest version.'
---
= Deployment workflow for existing users of ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
The 9.x releases of ONTAP tools for VMware vSphere support in-place upgrade to the latest version.

The earlier releases of individual applications like ONTAP tools use a different upgrade process. If you have VSC or VASA Provider or SRA installed in your setup, then you should perform the following operations:

. Deploy the latest release of ONTAP tools.
. Migrate any existing configuration data.
+
The configuration data includes storage system credentials, as well as preferences found in the `kaminoprefs.xml` and `vscPreferences.xml`   files.

link:../configure/reference_set_ipv4_or_ipv6.html[Set IPv4 or IPv6 using the preferences file]

In many cases, you might not need to migrate configuration data. However, if you have customized the preferences files earlier, you might want to review them and make similar changes to the newly deployed ONTAP tools. You can perform one of the following:

* Use https://mysupport.netapp.com/tools/index.html[NetApp Import Utility for SnapCenter and Virtual Storage Console] to migrate storage system credentials from VSC 6.X and SRA 4.X to the new deployment.
* Add the storage systems to the newly deployed ONTAP tools and specify the credentials as you add them.

If you are upgrading from VASA Provider 6.X, you should unregister VASA Provider before upgrading. See the documentation for your current release for more details.

If you are also upgrading from SRA 4.0 or earlier:

* If you are using SRA 4.0P1, then you must first upgrade to SRA9.6 and only then you can perform an in-place upgrade of the SRA 9.6 to the latest release.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html[Upgrade to the latest release of ONTAP tools]

* If you are using SRA 2.1 or 3.0, you should first make note of existing site configuration details.
+
_Installation and Setup Guide for Storage Replication Adapter 4.0 for ONTAP_ has the detailed instructions in the "Upgrade Overview" section. These SRA releases also use the VASA Provider, so you must unregister VASA Provider and then deploy the latest version of ONTAP tools. The previous release of the server (`.ova`) can be removed when the upgrade is complete.

For any SRA upgrade, the SRA software (the adapter on the Site Recovery Manager server, installed by the `.msi` file) should be removed from the Site Recovery Manager server. You can use the Windows system control panel to uninstall the software and then install the latest SRA software on the SRA server using the `.msi` file.

If you have the VASA Provider deployment, then after the upgrade from existing setup, you must configure the memory size for your ONTAP tools to be 12GB using the `Edit Settings` option. You must also modify the virtual memory reservation. The virtual machine must be powered off to modify the memory size.

If you are having 7.2 or 7.2.1 release of ONTAP tools in your setup, then you cannot directly upgrade to 9.7P1 or later release of the ONTAP tools. You must first upgrade your existing setup to the 9.7 release of ONTAP tools and then upgrade to the latest release.

If you are going to deploy the latest release of ONTAP tools, you must see the topic "`Requirements for deploying the ONTAP tools.`" The topic "`Upgrading to the 9.8 release of ONTAP tools`" has information on performing an in-place upgrade.

*Related information*

https://mysupport.netapp.com/site/tools
