---
permalink: deploy/concept_standard_roles_packaged_with_virtual_appliance_for_vsc_vp_and_sra.html
sidebar: sidebar
keywords: 
summary: 'To simplify working with vCenter Server privileges and role-based access control \(RBAC\), \(VSC\) provides standard VSC roles that enable you to perform key VSC tasks. There is also a read-only role that enables you to view VSC information, but not perform any tasks.'
---
= Standard roles packaged with ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
To simplify working with vCenter Server privileges and role-based access control (RBAC), (VSC) provides standard VSC roles that enable you to perform key VSC tasks. There is also a read-only role that enables you to view VSC information, but not perform any tasks.

The standard VSC roles have both the required VSC-specific privileges and the native vCenter Server privileges that are required for users to perform VSC tasks. In addition, the roles are set up so that they have the required privileges across all supported versions of the vCenter Server.

As an administrator, you can assign these roles to users, as required.

NOTE: When you upgrade VSC to the latest version, the standard roles are automatically upgraded to work with the new version of VSC.

You can view the VSC standard roles by clicking *Roles* on the vSphere ClientHome page.

The roles that VSC provides enable you to perform the following tasks:

|===
| Role| Description
a|
VSC Administrator
a|
Provides all of the native vCenter Server privileges and VSC-specific privileges that are required to perform all VSC tasks.
a|
VSC Read-only
a|
Provides read-only access to VSC. These users cannot perform any VSC actions that are access-controlled.

a|
VSC Provision
a|
Provides all of the native vCenter Server privileges and VSC-specific privileges that are required to provision storage. You can perform the following tasks:

* Create new datastores
* Destroy datastores
* View information about storage capability profiles

|===
