---
permalink: deploy/reference_port_requirements_for_vsc.html
sidebar: sidebar
keywords: port requirements
summary: 'By default, Virtual Storage Console \(VSC\) uses designated ports to enable communication between its components, which include storage systems and the VMware vCenter Server. If you have firewalls enabled, you must ensure that the firewalls are set to allow exceptions.'
---
= Port requirements for VSC
:icons: font
:imagesdir: ../media/

[.lead]
By default, Virtual Storage Console (VSC) uses designated ports to enable communication between its components, which include storage systems and the VMware vCenter Server. If you have firewalls enabled, you must ensure that the firewalls are set to allow exceptions.

For firewalls other than Windows, you should manually grant access to specific ports that VSC uses. If you do not grant access to these ports, an error message such as the following is displayed.

`Unable to communicate with the server.`

VSC uses the following default bidirectional TCP ports:

|===
| *Default port number*|*Description*
a|
9083
a|
When enabled, both VASA Provider and Storage Replication Adapter (SRA) use this port to communicate with the vCenter Server. This port is also required for obtaining the TCP/IP settings.
a|
443
a|
Depending on how you have configured your credentials, the VMware vCenter Server and the storage systems listen for secure communications on this port.

a|
8143
a|
VSC listens for secure communications on this port.
a|
7
a|
VSC sends an echo request to ONTAP to verify reachability and is required only when adding storage system and can be disabled later.
|===
NOTE: You should have enabled Internet Control Message Protocol (ICMP) before deploying the ONTAP tools.

If ICMP is disabled, then the initial configuration of ONTAP tools fails, and VSC cannot start the VSC and VASA Provider services after deployment. You must manually enable the VSC and VASA Provider services after deployment.
