---
permalink: deploy/reference_considerations_for_deploying_virtual_appliance_for_vsc_vasa_provider_and_sra.html
sidebar: sidebar
keywords: Virtual Storage Console,Storage Replication Adapter
summary: 'Before you deploy ONTAP tools for VMware vSphere, it is good practice to plan your deployment and decide how you want to configure ONTAP tools in your environment.'
---
= Considerations for deploying ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
Before you deploy ONTAP tools for VMware vSphere, it is good practice to plan your deployment and decide how you want to configure ONTAP tools in your environment.

The following table presents an overview of what you should consider before you deploy ONTAP tools.

|===
| *Considerations*| *Description*
a|
First-time deployment of ONTAP tools
a|
The deployment of the ONTAP tools automatically installs the VSC features.

link:../deploy/concept_deploy_or_upgrade_ontap_tools.html[Deploying or upgrading ONTAP tools for VMware vSphere]

link:../deploy/concept_installation_workflow_for_new_users.html[Deployment workflow for new users of ONTAP tools for VMware vSphere]

a|
Upgrading from an existing deployment of VSC
a|
The upgrade procedure from an existing deployment of VSC to ONTAP tools depends on the version of VSC, and whether you have deployed ONTAP tools. The deployment workflows and upgrade section has more information.

link:concept_installation_workflow_for_existing_users_of_vsc.html[Deployment workflow for existing users of ONTAP tools]

Best practices before an upgrade:

* You should record information about the storage systems that are being used and their credentials.
+
After the upgrade, you should verify that all of the storage systems were automatically discovered and that they have the correct credentials.

* If you modified any of the standard VSC roles, you should copy those roles to save your changes.
+
VSC overwrites the standard roles with the current defaults each time you restart the VSC service.

a|
Regenerating an SSL certificate for VSC
a|
The SSL certificate is automatically generated when you deploy the ONTAP tools. You might have to regenerate the SSL certificate to create a site-specific certificate.

link:../configure/task_regenerate_an_ssl_certificate_for_vsc.html[Regenerate an SSL certificate for Virtual Storage Console]

a|
Setting ESXi server values
a|
Although most of your ESXi server values are set by default, it is a good practice to check the values. These values are based on internal testing. Depending on your environment, you might have to change some of the values to improve performance.

* link:../configure/task_configure_esx_server_multipathing_and_timeout_settings.html[Configure ESXi server multipathing and timeout settings]
* link:../configure/reference_esxi_host_values_set_by_vsc_for_vmware_vsphere.html[ESXi host values set using ONTAP tools for VMware vSphere]

a|
Guest operating system timeout values
a|
The guest operating system (guest OS) timeout scripts set the SCSI I/O timeout values for supported Linux, Solaris, and Windows guest operating systems to provide correct failover behavior.
|===
The following table presents an overview of what you require to configure the ONTAP tools.

|===
| *Considerations*| *Description*
a|
Requirements of role-based access control (RBAC)
a|
VSC supports both vCenter Server RBAC and ONTAP RBAC. The account used to register VSC to vCenter Server (`https://<appliance_ip>:8143/Register.html`) must be a vCenter Server administrator (assigned to the vCenter Server administrator or administrator role). If you plan to run VSC as an administrator, you must have all of the required permissions and privileges for all of the tasks.

If your company requires that you restrict access to vSphere objects, you can create and assign standard VSC roles to users to meet the vCenter Server requirements.

You can create the recommended ONTAP roles by using ONTAP System Manager using the JSON file provided with the ONTAP tools.

If a user attempts to perform a task without the correct privileges and permissions, the task options are grayed out.

* link:../concepts/concept_standard_roles_packaged_with_virtual_appliance_for_vsc_vp_and_sra.html[Standard roles packaged with ONTAP tools]
* link:../concepts/concept_ontap_role_based_access_control_feature_for_ontap_tools.html[Permissions for ONTAP storage systems and vSphere objects]

a|
ONTAP version
a|
Your storage systems must be running ONTAP 9.3, 9.5, 9.6, 9.7, 9.8P1 or later.
a|
Storage capability profiles
a|
To use storage capability profiles or to set up alarms, you must enable VASA Provider for ONTAP. After you enable VASA Provider, you can configure VMware Virtual Volumes (vVols) datastores, and you can create and manage storage capability profiles and alarms. The alarms warn you when a volume or an aggregate is at nearly full capacity or when a datastore is no longer in compliance with the associated storage capability profile.

|===
