---
permalink: deploy/task_registering_oncommand_api_services_with_the_virtual_appliance_for_vsc_vasa_provider_and_sra.html
sidebar: sidebar
keywords: virtual volume datastores
summary: 'If you are using ONTAP 9.6 or earlier, then the vVol dashboard can display the details of VMware Virtual Volumes \(vVols\) datastores and virtual machines only if you have registered for VASA Provider to obtain data for the vVols VM and datastore reports.'
---
= Registering with ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
If you are using ONTAP 9.6 or earlier, then the vVol dashboard can display the details of VMware Virtual Volumes (vVols) datastores and virtual machines only if you have registered for VASA Provider to obtain data for the vVols VM and datastore reports.

You must have downloaded 2.1 or later from .

NOTE: The vVol dashboard displays performance metrics only when the SAN vVols datastores and virtual machines are configured using ONTAP 9.3 or later.

. From the ONTAP toolsHome page, click *Settings*.
. Click *Manage Extension* in the Administrative Settings tab.
. Use the *Register OnCommand API Services* slider to enable .
. Enter the IP address, service port, and credentials for .
+
You can also use the Manage VASA Provider Extensions dialog box for the following modifications:

 ** To update registration when there is any change to the credentials.
 ** To unregister when you no longer require the vVol dashboard.
+
You must clear the Register OnCommand API Services checkbox to remove the registration for VASA Provider.

. Click *Apply*.
+
The vVol dashboard displays the metrics for ONTAP 9.6 or earlier SAN vVol datastores only after the registration of is complete.

*Related information*

https://mysupport.netapp.com/site/global/dashboard[NetApp Support]
