---
permalink: deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html
sidebar: sidebar
keywords: clean up browser cache
summary: 'If plug-ins are not updated automatically after deploying or upgrading ONTAP tools, you should clean up the cached download plug-in packages on the browser and on the vCenter Serverto resolve vCenter Server plug-in issues.'
---
= Clear the vSphere cached downloaded plug-in packages
:icons: font
:imagesdir: ../media/
[.lead]
If plug-ins are not updated automatically after deploying or upgrading ONTAP tools, you should clean up the cached download plug-in packages on the browser and on the vCenter Server to resolve vCenter Server plug-in issues.

*Steps*

. Logout from your existing vSphere web client or vSphere-UI.
. Remove the browser cache.
. Remove the vSphere Client cached plug-in packages. For VCSA, Perform the following:

 .. SSH into the VCSA appliance.
 .. Stop the VMware vSphere Client service:
 `service-control --stop vsphere-ui`
 .. Change directories to the vCenter client UI extensions directory: `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`
 .. Remove the cached plug-in packages specific to NetApp using the `rm -rf` commands:
+
`rm -rf com.netapp.nvpf.webclient-*`
+
`rm -rf com.netapp.vasa.vvol.webclient-*`
+
`rm -rf com.netapp.vsch5-*`
.. Start the VMware vSphere Client service:
`service-control --start vsphere-ui`

