---
permalink: deploy/task_deploy_ontap_tools.html
sidebar: sidebar
keywords:
summary: 'You should deploy ONTAP tools in your environment, and specify the required parameters, to be able to use the appliance.'
---
= How to deploy ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You should deploy ONTAP tools in your environment, and specify the required parameters, to be able to use the appliance.

*What you will need*

* You must be running a supported release of vCenter Server.
+
NOTE: ONTAP tools can be registered either with a Windows deployment of vCenter Server or a VMware vCenter Server Virtual Appliance (vCSA) deployment.
+
https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT[Interoperability Matrix Tool^]

* You must have configured and set up your vCenter Server environment.
* You must have set up an ESXi host for your virtual machine.
* You must have downloaded the _.ova_ file.
* You must have the administrator login credentials for your vCenter Server instance.
* You should have logged out of and closed all of the browser sessions of vSphere Client, and deleted the browser cache to avoid any browser cache issue during the deployment of ONTAP tools.
* You must have enabled Internet Control Message Protocol (ICMP).
+
If ICMP is disabled, then the initial configuration of ONTAP tools fails, and VSC cannot start the VSC and VASA Provider services after deployment. You must manually enable the VSC and VASA Provider services after deployment.

*About this task*

If you are deploying a fresh installation of ONTAP tools, then VASA Provider is enabled by default. But in case of an upgrade from an earlier release of the ONTAP tools, the state of VASA Provider is retained and you might need to enable VASA Provider manually.

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html[Enable VASA Provider for configuring virtual datastores]

*Steps*

. Log in to the vSphere Client.
. Select *Home* > *Host and Clusters*.
. Right-click the required datacenter, and then click *Deploy OVF template...*.
. Select the applicable method to provide the deployment file for ONTAP tools, and then click *Next*.
+
|===
| *Location* | *Action*
a|
URL
a|
Provide the URL for the _.ova_ file for ONTAP tools.
a|
Folder
a|
Extract the .zip file, which contains the .ova file onto your local system. On the Select an OVF template page, specify the location of the .ova file inside the extracted folder.
|===

. Enter the details to customize the deployment wizard.
+
(Optional) In the Configure vCenter or Enable VCF section, select the *Enable VMware Cloud Foundation (VCF)* checkbox and provide a password for ONTAP tools credentials.
You do not need to provide IP address but providing a password is mandatory.
See the following for complete details.

* link:../deploy/reference_considerations_for_deploying_ontap_tools_for_vmware_vsphere.html[Deployment customization considerations]
* link:../deploy/vmware_cloud_foundation_mode_deployment.html[VMware Cloud Foundation mode of deployment for ONTAP tools]

. Review the configuration data, and then click *Next* to finish deployment.
+
As you wait for deployment to finish, you can view the progress of the deployment from the Tasks tab.

. Power on the ONTAP tools virtual machine, and then open a console of the virtual machine running the ONTAP tools.
. Verify that ONTAP tools is running after the deployment is completed.
. If ONTAP tools is not registered with any vCenter Server, use `\https://appliance_ip:8143/Register.html` to register the VSC instance. The Register.html redirects you to the swagger page. From ONTAP tools 9.12 onwards the registration of ONTAP tools with vCenter happens from the swagger page. 
+
Use the POST API to register ONTAP tools with vCenter from 9.12 onwards.
+
----
/2.0/plugin/vcenter
----

. Log out and re-log in to the vSphere Client to view the deployed ONTAP tools.
+
It might take a few minutes for the plug-in to be updated in the vSphere Client.
+
*Troubleshooting:* If you cannot view the plug-in even after logging in, you must clean the vSphere Client cache.
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html[Clear the vSphere cached downloaded plug-in packages]

link:../deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html[Enable VASA Provider for configuring virtual datastores]

*Related information*

https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Software%2FVirtual_Storage_Console_for_VMware_vSphere%2FError_during_fresh_deployment_of_virtual_appliance_for_VSC%252C_VASA_Provider%252C_and_SRA[Error during fresh deployment of virtual appliance for VSC, VASA Provider, and SRA]
