---
permalink: protect/task_map_storage_policies.html
sidebar: sidebar
keywords:
summary: 'You should map the storage policies on the protected site to the storage policies on the recovery site for your recovery plan to place the recovered virtual machines on the appropriate datastores based on your mappings. After the virtual machine is recovered on recovery site, mapped VM Storage Policy will be assigned to virtual machine.'
---
= Map storage policies
:icons: font
:imagesdir: ../media/

[.lead]
You should map the storage policies on the protected site to the storage policies on the recovery site for your recovery plan to place the recovered virtual machines on the appropriate datastores based on your mappings. After the virtual machine is recovered on recovery site, mapped VM Storage Policy will be assigned to virtual machine.

*Steps*

. On the vSphere Client, click *Site Recovery* > *Open Site Recovery*.
. In the Site Pair tab, click *Configure* > *Storage Policy Mappings*.
. Select the required site, and then click *New* to create a new mapping.
. Select the option *Automatically prepare mappings for storage policies with matching names*, and then click *NEXT*.
+
SRM will select storage policies on the protected site for which a storage policy with the same name exists on the recovery site. You can also select the manual mapping option to select multiple storage policies.

. Click *Add mappings*, and the click *NEXT*.
. In the *Reverse mapping* section, select the required check boxes for mapping, and then click *NEXT*.
. In the *Ready to complete* section, review your selections and click *FINISH*.
