---
permalink: protect/task_update_sra_credentials.html
sidebar: sidebar
keywords: SRA credentials, updating
summary: 'For SRM to communicate with SRA, you should update SRA credentials on the SRM server if you have modified the credentials.'
---
= Update SRA credentials
:icons: font
:imagesdir: ../media/

[.lead]
For SRM to communicate with SRA, you should update SRA credentials on the SRM server if you have modified the credentials.

You need to delete the SRM machine folder cached ONTAP tools username password and reinstall the SRA.

*What you will need*

You should have executed the steps mentioned in the topic link:../protect/task_configure_sra_on_srm_appliance.html[Configuring SRA on the SRM Appliance]

*Steps*

. Run the following commands to delete the SRM machine folder cached ONTAP tools username password:
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd /conf`
.. `rm -rf *`
. Run the perl command to configure SRA with the new credentials:
.. `cd ..`
.. `perl command.pl -I <otv-IP> administrator <otv-password>`. You need to have a single quote around the password value. 
+
A success message confirming that the storage credentials are stored is displayed. SRA can communicate with SRA server using the provided IP address, port and credentials.
