---
permalink: protect/task_verify_the_replicated_storage_environment.html
sidebar: sidebar
keywords:
summary: 'You must verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter \(SRA\). The replicated storage system must be discoverable by both the protected site and the recovery site.'
---
= Verify replicated storage systems
:icons: font
:imagesdir: ../media/

[.lead]
You must verify that the protected site and recovery site are successfully paired after configuring Storage Replication Adapter (SRA). The replicated storage system must be discoverable by both the protected site and the recovery site.

*What you will need*

* You must have configured your storage system.
* You must have paired the protected site and recovery site by using the SRM array manager.
* You must have enabled FlexClone license and SnapMirror license before performing the test failover operation and failover operation for SRA.

*Steps*

. Log in to your vCenter Server.
. Navigate to *Site Recovery* > *Array Based Replication*.
. Select the required SVM, and then verify the corresponding details in the Array Pairs.
+
The storage systems must be discovered at the protected site and recovery site with the Status as "`Enabled`".
