---
permalink: protect/task_enable_storage_replication_adapter.html
sidebar: sidebar
keywords:
summary: 'The ONTAP tools for VMware vSphere provides the option to enable the SRA capability to be used with ONTAP tools to configure disaster recovery.'
---
= Enable SRA to protect datastores
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere provides the option to enable the SRA capability to be used with ONTAP tools to configure disaster recovery.

*What you will need*

* You must have set up your vCenter Server instance and configured ESXi.
* You must have deployed ONTAP tools.
* You must have downloaded the `.tar.gz` file for SRM appliance only if you want to configure the Site Recovery Manager (SRM) disaster recovery solution.
+
https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-B3A49FFF-E3B9-45E3-AD35-093D896596A0.html[Site Recovery Manager Installation and Configuration Site Recovery Manager 8.2] has more information.

*About this task*

The flexibility to enable VASA Provider and SRA capabilities enables you to execute only the workflows that you require for your enterprise.

*Steps*

. Log in to the web user interface of VMware vSphere.
. From the vSphere Client, select *Menu* > *NetApp ONTAP tools*.
. Click *Settings*.
. Click *Manage Capabilities* in the *Administrative Settings* tab.
. In the *Manage Capabilities* dialog box, select the SRA extension want to enable.
. Enter the IP address of ONTAP tools and the administrator password, and then click *Apply*.
. You can use one of the following methods to deploy SRA:
+
*For SRM appliance*

 .. Access the VMware SRM Appliance Management Interface using the URL: https://:<srm_ip>:5480, and then go to Storage Replication Adapters in VMware SRM Appliance Management Interface.
 .. Click *New Adapter*.
 .. Upload the _.tar.gz_ installer for the SRA plug-in to SRM.
 .. Rescan the adapters to verify that the details are updated in the SRM Storage Replication Adapters page.

You must log out of the vSphere Client, and then log in again to verify that your selected extension is available for configuration.

*Related information*

link:../concepts/concept_manage_disaster_recovery_setup_using_srm.html[Configure Storage Replication Adapter for disaster recovery]
