---
permalink: concepts/concept_virtual_storage_console_overview.html
sidebar: sidebar
keywords:
summary: 'The ONTAP tools for VMware vSphere provides end-to-end life cycle management for virtual machines in VMware environments that use NetApp storage systems. It simplifies storage and data management for VMware environments by enabling administrators to directly manage storage within the vCenter Server.'
---
= ONTAP tools Overview
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere provides end-to-end life cycle management for virtual machines in VMware environments that use NetApp storage systems. It simplifies storage and data management for VMware environments by enabling administrators to directly manage storage within the vCenter Server.

With vSphere 6.5, VMware introduced a new HTML5-based client called vSphere Client. The 9.6 and later releases of ONTAP tools support only vSphere Client. The ONTAP tools integrates with vSphere Client and enables you to use single sign-on (SSO) services. In an environment with multiple vCenter Server instances, each vCenter Server instance that you want to manage must have its own registered instance of VSC.

Each component in ONTAP tools provides capabilities to help manage your storage more efficiently.

== Virtual Storage Console (VSC)

VSC enables you to perform the following tasks:

* Add storage controllers, assign credentials, and set up permissions for storage controllers of VSC, that both SRA and VASA Provider can leverage
* Provision datastores
* Monitor the performance of the datastores and virtual machines in your vCenter Server environment
* Control administrator access to the vCenter Server objects by using role-based access control (RBAC) at two levels:
 ** vSphere objects, such as virtual machines and datastores
+
These objects are managed by using the vCenter Server RBAC.

 ** ONTAP storage
+
The storage systems are managed by using ONTAP RBAC.
* View and update the host settings of the ESXi hosts that are connected to NetApp storage

VSC provisioning operations benefit from using the NFS Plug-in for VMware vStorage APIs for Array Integration (VAAI). The NFS Plug-in for VAAI is a software library that integrates the VMware Virtual Disk Libraries that are installed on the ESXi host. The VMware VAAI package enables the offloading of certain tasks from the physical hosts to the storage array. You can perform tasks such as thin provisioning and hardware acceleration at the array level to reduce the workload on the ESXi hosts. The copy offload feature and space reservation feature improve the performance of VSC operations.

The NetApp NFS Plug-in for VAAI is not shipped with VSC. But you can download the plug-in installation package and obtain the instructions for installing the plug-in from the NetApp Support Site.

== VASA Provider

VASA Provider for ONTAP uses VMware vSphere APIs for Storage Awareness (VASA) to send information about storage used by VMware vSphere to the vCenter Server. ONTAP tools has VASA Provider integrated with VSC. VASA Provider enables you to perform the following tasks:

* Provision VMware Virtual Volumes (vVols) datastores
* Create and use storage capability profiles that define different storage service level objectives (SLOs) for your environment
* Verify for compliance between the datastores and the storage capability profiles
* Set alarms to warn you when volumes and aggregates are approaching the threshold limits
* Monitor the performance of virtual machine disks (VMDKs) and the virtual machines that are created on vVols datastores

If you are using ONTAP 9.6 or earlier, then VASA Provider communicates with the vCenter Server by using VASA APIs and communicates with ONTAP by using NetApp APIs called ZAPIs. To view the vVols dashboard for ONTAP 9.6 and earlier, you must have installed and registered OnCommand API Services with your vCenter Server. If you are using ONTAP 9.7 and later versions, then you do not require OnCommand API Services to be registered with VASA Provider to view the vVols dashboard.

NOTE: For ONTAP 9.6 and earlier, VASA Provider requires a dedicated instance of OnCommand API Services. One instance of OnCommand API Services cannot be shared with multiple VASA Provider instances.

== Storage Replication Adapter (SRA)

When SRA is enabled and used in conjunction with VMware Site Recovery Manager (SRM), you can recover the vCenter Server datastores and virtual machines in the event of a failure. SRA enables you to use array based replication (ABR) for protected sites and recovery sites for disaster recovery in the event of a failure.

*Related information*

[ntap-prodlib-oc-api-svcs]

https://mysupport.netapp.com/site/global/dashboard[NetApp Support]
