---
permalink: concepts/reference_product_level_privilege_required_by_ontap_tools_for_vmware_vsphere.html
sidebar: sidebar
keywords:
summary: 'To access the ONTAP tools for VMware vSphere GUI, you must have the product-level, ONTAP tools-specific View privilege assigned at the correct vSphere object level. If you log in without this privilege, ONTAP tools display an error message when you click the NetApp icon and prevents you from accessing ONTAP tools.'
---
= Product-level privilege required by ONTAP tools for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
To access the ONTAP® tools for VMware vSphere GUI, you must have the product-level, ONTAP tools-specific View privilege assigned at the correct vSphere object level. If you log in without this privilege, ONTAP tools display an error message when you click the NetApp icon and prevents you from accessing ONTAP tools.
In *View* privilege, you can access the ONTAP tools GUI. This privilege does not enable you to perform tasks within ONTAP tools. To perform any ONTAP tools tasks, you must have the correct ONTAP tools-specific and native vCenter Server privileges for those tasks.

The assignment level determines which portions of the UI you can see. Assigning the View privilege at the root object (folder) enables you to enter ONTAP tools by clicking the NetApp icon.

You can assign the View privilege to another vSphere object level; however, doing that limits the ONTAP tools menus that you can see and use.

The root object is the recommended place to assign any permission containing the View privilege.