---
permalink: configure/reference_configure_the_vsc_preferences_files.html
sidebar: sidebar
keywords: preferences files
summary: 'The preferences files contain settings that control ONTAP® tools for VMware vSphere operations. Under most circumstances, you do not have to modify the settings in these files. It is helpful to know which preference files ONTAP tools uses.'
---
= Configure the ONTAP tools preferences files
:icons: font
:imagesdir: ../media/

[.lead]
The preferences files contain settings that control ONTAP tools for VMware vSphere operations. Under most circumstances, you do not have to modify the settings in these files. It is helpful to know which preference files ONTAP tools uses.

ONTAP tools has several preference files. These files include entry keys and values that determine how ONTAP tools performs various operations. The following are some of the preference files that ONTAP tools uses:

`/opt/netapp/vscserver/etc/kamino/kaminoprefs.xml`

`/opt/netapp/vscserver/etc/vsc/vscPreferences.xml`

You might have to modify the preferences files in certain situations. For example, if you use iSCSI, NFS, or NVMe/FC and the subnet is different between your ESXi hosts and your storage system, you have to modify the preferences files. If you do not modify the settings in the preferences file, datastore provisioning fails because ONTAP tools cannot mount the datastore.
