---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html
sidebar: sidebar
keywords: virtual volume datastores
summary: 'If you are using ONTAP 9.6 or earlier, then the vVols dashboard can display the details of VMware Virtual Volumes \(vVols\) datastores and virtual machines only if you have registered OnCommand API Services for VASA Provider to obtain data for the vVols VM and datastore reports.'
---
= Register OnCommand API Services with ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
If you are using ONTAP 9.6 or earlier, then the vVols dashboard can display the details of VMware Virtual Volumes (vVols) datastores and virtual machines only if you have registered OnCommand API Services for VASA Provider to obtain data for the vVols VM and datastore reports.

*What you will need*

You must have downloaded OnCommand API Services 2.1 or later from the NetApp Support Site.

NOTE: The vVols dashboard displays performance metrics only when the SAN vVols datastores and virtual machines are configured using ONTAP 9.3 or later.

*Steps*

. From the ONTAP tools home page, click *Settings*.
. Click *Manage Extension* in the Administrative Settings tab.
. Use the Register OnCommand API Services slider to enable OnCommand API Services.
. Enter the IP address, service port, and credentials for OnCommand API Services.
+
You can also use the Manage VASA Provider Extensions dialog box for the following modifications:

 ** To update OnCommand API Services registration when there is any change to the credentials.
 ** To unregister OnCommand API Services when you no longer require the vVols dashboard.
+
You must clear the Register OnCommand API Services checkbox to remove the OnCommand API Services registration for VASA Provider.

. Click *Apply*.
+
The vVols dashboard displays the metrics for ONTAP 9.6 or earlier SAN vVols datastores only after the registration of OnCommand API Services is complete.

*Related information*

https://mysupport.netapp.com/site/global/dashboard[NetApp Support]
