---
permalink: configure/task_enable_datastore_mounting_across_different_subnets.html
sidebar: sidebar
keywords:
summary: 'If you use iSCSI or NFS and the subnet is different between your ESXi hosts and your storage system, you have to modify the ONTAP® tools for VMware vSphere preferences files. If you do not modify the preferences file, then datastore provisioning fails because Virtual Storage Console \(VSC\) cannot mount the datastore.'
---
= Enable datastore mounting across different subnets
:icons: font
:imagesdir: ../media/

[.lead]
If you use iSCSI or NFS and the subnet is different between your ESXi hosts and your storage system, you have to modify the ONTAP® tools for VMware vSphere preferences files. If you do not modify the preferences file, then datastore provisioning fails because Virtual Storage Console (VSC) cannot mount the datastore.

*About this task*

When datastore provisioning fails, VSC logs the following error messages:

`Unable to continue. No ip addresses found when cross-referencing kernel ip addresses and addresses on the controller.

Unable to find a matching network to NFS mount volume to these hosts.`

*Steps*

. Log in to your vCenter Server instance.
. Launch the maintenance console using your unified appliance virtual machine.
+
link:reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html[Maintenance Console of ONTAP tools for VMware vSphere]

. Enter `4` to access the Support and Diagnostics option.
. Enter `2` to access the Access Diagnostic Shell option.
. Enter `vi /opt/netapp/vscserver/etc/kamino/kaminoprefs.xml` to update the `kaminoprefs.xml` file.
. Update the `kaminoprefs.xml` file.
+
|===
| *If you use...*| *Do this...*
a|
iSCSI
a|
Change the value of the entry key `default.allow.iscsi.mount.networks` from ALL to the value of your ESXi host networks.
a|
NFS
a|
Change the value of the entry key `default.allow.nfs.mount.networks` from ALL to the value of your ESXi host networks.
|===
The preferences file includes sample values for these entry keys.
+
NOTE: The value "`ALL`" does not mean all networks. The "`ALL`" value enables all of the matching networks, between the host and the storage system, to be used for mounting datastores. When you specify host networks, then you can enable mounting only across the specified subnets.

. Save and close the `kaminoprefs.xml` file.
