---
permalink: configure/task_enable_vasa_provider_for_configuring_virtual_datastores.html
sidebar: sidebar
keywords:
summary: 'The ONTAP tools for VMware vSphere has the VASA Provider capability enabled by default. You can configure VMware Virtual Volumes \(vVols\) datastores with required storage capability profiles for each vVols datastore.'
---
= *Enable VASA Provider for configuring virtual datastores*
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP tools for VMware vSphere has the VASA Provider capability enabled by default. You can configure VMware Virtual Volumes (vVols) datastores with required storage capability profiles for each vVols datastore.

*What you will need*

* You must have set up your vCenter Server instance and configured ESXi.
* You must have deployed ONTAP tools .

*About this task*

If the VASA Provider capability is disabled before upgrading to the 9.7.1 release of ONTAP tools , the VASA Provider capability remains disabled after the upgrade. This release allows you to enable vVols replication feature for vVols datastores.

*Steps*

. Log in to the web user interface of VMware vSphere.
. From the vSphere Client, click *Menu* > *ONTAP tools Console*.
. Click *Settings*.
. Click *Manage Capabilities* in the Administrative Settings tab.
. In the Manage Capabilities dialog box, select the VASA Provider extension to enable.
. If you want to use replication capability for vVols datastores, then use the *Enable vVols replication* toggle button.
. Enter the IP address of ONTAP tools and the administrator password, and then click *Apply*.
+
NOTE: If VASA Provider status displays as "`Offline`" even after enabling the VASA Provider extesnsion, then check the /var/log/vmware/vmware-sps/sps.log file for any connection errors with VASA Provider or restart the "`vmware-sps`" service.

If you are using ONTAP 9.6 or earlier clusters, then you must register OnCommand API Services with VASA Provider to get details of vVols datastores and virtual machines used in the SAN vVols VM and SAN vVols datastore reports. But if you are using ONTAP 9.7 or later, then you do not need to register OnCommand API Services with VASA Provider.
