---
permalink: manage/task_change_the_administrative_password.html
sidebar: sidebar
keywords:
summary: 'You can change the administrator password of ONTAP tools post deployment using the maintenance console.'
---
= Change the administrator password
:icons: font
:imagesdir: ../media/

[.lead]
You can change the administrator password of ONTAP tools post deployment using the maintenance console. Password expires after 90 days.

*Steps*

. From the vCenter Server, open a console to the ONTAP tools.
. Log in as the maintenance user.
. Enter `1` in the maintenance console to select Application Configuration.
. Enter `6` to select *Change 'administrator' user password*.
. Enter a password with minimum eight characters and maximum 30 characters. The password must contains a minimum of one upper, one lower, one digit, and one special character. Password expiry warning is shown after 75 days of resetting the password. The new password cannot be same as the last used password.
+
If you do not follow the password recommendations, the maintenance console option is limited to change password.
When the password has expired, you are prompted to change the password.
. Enter `y` in the confirmation dialog box.
